### ISSUE TITLE
Rate limited by Github

### ISSUE THREAD

**Issue by sachincool** [imranismail/setup-kustomize#119]
![image](https://user-images.githubusercontent.com/25671488/113845334-04c6a700-97b3-11eb-97aa-ee08df75339d.png)

We're using this action in production and have been facing a lot of Rate limiting by [Github Api ](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting)
seems to be connected with the unauthorized Api rate limit which is 60/hr 
can we include access_token in this action to make authorize calls?

**Comment by sachincool** [comment]
possibly, the cause of rate limit is this call
[Oktokit.releases](https://github.com/imranismail/setup-kustomize/blob/master/dist/index.js#L9201)

**Comment by operzia-apptio** [comment]
My team has also hit this API Rate Limit error
I've confirmed that this action "setup-kustomize" is the source (logged before and after the API rate limit count)

- this action counts for 7 of the 60 limit... run a few times in a hour and build will fail (until limit is reset each hour)
- other actions in our flow do not have this issue (can be fixed as @sachincool suggests)

Add this before and after to see the rate limit impact:
`      - name: GitHub Rate Limit (Start)
        run: |
          curl \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/rate_limit`

**Comment by imranismail** [comment]
Can ya'll try v1.5.4, this should fix it

**Comment by operzia-apptio** [comment]
Thanks I will try that out...
Note: GitHub Marketplace says to use v1 (latest)
https://github.com/marketplace/actions/setup-kustomize

Is the version something you need to update?

**Comment by imranismail** [comment]
@operzia-apptio I've moved the v1 tag to the latest commit, you should be good

**Comment by operzia-apptio** [comment]
@imranismail - I've tested **v1.5.4** and still has same issue => 6 requests used by '**setup-kustomize**' action (see pic)
You can easily test yourself (see my comment above on the Action cmd to add before & after your Action)
![image](https://user-images.githubusercontent.com/62717472/117899580-43e98b80-b27c-11eb-865a-ded8451451e9.png)

**Comment by imranismail** [comment]
Thanks @operzia-apptio,

I've created another release that addresses this, the action will now by default uses the repo token and that should increase the api limit significantly.

I've also added a throttle plugin that throttles requests to github api, that should make this action a good citizen in Github's POV.

Please try it out at v1.6.0

**Comment by operzia-apptio** [comment]
@imranismail - Perfect. Confirmed 0 api counts "used" with **v1.6.0** updates
