### ISSUE TITLE
Make 'fail-fast: true' the default behavior as major version update

### ISSUE THREAD

**Issue by dlemfh** [imranismail/setup-kustomize#275]
Hey @imranismail, hope this finds you well.

As you pointed out in the README.md, the default `false` behavior of `fail-fast` might accrue a long and expensive run time.

If the default behavior of `fail-fast` were `true`, when the rate-limit is reached, users would instantly be notified of the failed workflow run.
Users would then be allowed to act accordingly. (Some may simply wait it out; others may choose to explicitly turn off `fail-fast`.)

On the other hand, if the default behavior of `fail-fast` is `false` (as it currently is now), when the rate-limit is reached,
the github workflow will ***silently*** run for a long time (theoretically up to an additional 1 hour) without any particular notice to the user.

Worst case scenario, github user will not notice anything until they are met with an expensive bill at the end of their payment cycle (= 1 month or, worse, 1 year).

**May I ask would you be willing to release a `v2` major version update (because it's a breaking change) where `fail-fast` default is `true`?**
I think it's good practice and in good faith to the community to have the less silently dangerous option be the default.

**Comment by imranismail** [comment]
Sure @dlemfh, I'll also make some improvement to the iterator to set a per page limit of 100
