### ISSUE TITLE
Fix deprecation warning for Node 16

### ISSUE THREAD

**Issue by mpicardvolvo** [imranismail/setup-kustomize#296]
**Current State**

Using setup-kustomize@2 results in a deprecation warning about Node 16:

<img width="1314" alt="Screenshot 2024-02-13 at 13 31 44" src="https://github.com/imranismail/setup-kustomize/assets/159451596/0bd4e9ee-3b0d-406d-adfc-4ff9e6d0c4eb">

**Expected State**

Using setup-kustomize must not have deprecation warnings about unsupported Node versions.

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

I searched the code for node 16 but did not find it to fix it. So I am not sure why this issue is appearing but please try to fix it because it seems like Node 16 is used somewhere.

**Comment by grantc** [comment]
@mpicardvolvo it's in https://github.com/imranismail/setup-kustomize/blob/v2.0.0/action.yml#L21. There's already a change in ```master```, I guess we just need to wait for a new tag.
