### ISSUE TITLE
Support `.tool-versions` file for kustomize version

### ISSUE THREAD

**Issue by ibratoev** [imranismail/setup-kustomize#7]
`.tool-versions` file is used by the popular ASDF tool (https://github.com/asdf-vm/asdf).

Check the `setup-ruby` action (https://github.com/ruby/setup-ruby) as an example.

**Comment by imranismail** [comment]
That's a great idea. I'm happy to accept contribution for this.

**Comment by imranismail** [comment]
Please use asdf action for this, it's better suited
