### ISSUE TITLE
Action doesn't install version 3.5.4

### ISSUE THREAD

**Issue by uwehdaub** [imranismail/setup-kustomize#85]
It used this action to install v3.5.4 and it failed (it only was successful, if it could get the tool from the cache).
Then I checked with v3.5.5 and it also failed.

While an installation of 3.8.5 was successful.

Is it possible, that the `paginate.iterator` only gets the first few pages and misses all the remaining?
https://github.com/imranismail/setup-kustomize/blob/91ce0fb611ee6f33e9f7f464c3c302564e7cbebd/src/installer.ts#L57

**Comment by imranismail** [comment]
I've deployed some changes related to the retry mechanism of the octokit client. Can you retry your action?

**Comment by uwehdaub** [comment]
Thanks for the quick response.

It seems to work now. I created a new self-hosted runner and the installation went through.

But I'm wondering, whether your change can explain, why it was repeatable failing before?

BR Uwe Daub

**Comment by imranismail** [comment]
Rate limited by Github because there are more pages to paginate till the action finds 3.5.4. To get around that I introduced retries with exponential back off.
